name: auto_mapper
version: 0.0.2+3
author: Liquid Thinking Ltd
description: A library for automatically mapping objects from one type to another
homepage: https://github.com/LiquidThinking/Dart-AutoMapper
dev_dependencies:
  unittest: any
